version: '3.1'

services:

  db:
    image: postgres
    # restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: bookstore
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
